// Regenerates the preset table in README.md from the ACTIVE (non-commented)
// presets in lib/bokeh_lava_gradient.dart.
//
// Block-commented presets (wrapped in /* ... */) are ignored, so only the
// presets that actually ship show up in the docs.
//
//   dart run tool/update_readme.dart
//
// Run from the project root. Exits non-zero on any problem (handy for CI).

import 'dart:io';

void main() {
  final srcFile = File('lib/bokeh_lava_gradient.dart');
  final readmeFile = File('README.md');
  if (!srcFile.existsSync() || !readmeFile.existsSync()) {
    stderr.writeln('error: run from the project root '
        '(needs lib/bokeh_lava_gradient.dart and README.md).');
    exit(1);
  }

  // Drop block comments so /* ...commented preset... */ entries are excluded.
  final src = srcFile
      .readAsStringSync()
      .replaceAll(RegExp(r'/\*.*?\*/', dotAll: true), '');

  final entry = RegExp(
    r'BokehTheme\.(\w+):\s*_BokehPreset\(\s*'
    r'Color\(0x([0-9A-Fa-f]{8})\)\s*,\s*'
    r'<Color>\[(.*?)\]\s*,\s*'
    r'([0-9.]+)\s*,\s*'
    r'Brightness\.(\w+)',
    dotAll: true,
  );
  final hex = RegExp(r'0x([0-9A-Fa-f]{8})');
  String h6(String h8) => '#${h8.substring(2).toUpperCase()}'; // 0xFFRRGGBB → #RRGGBB

  final rows = <String>[];
  for (final m in entry.allMatches(src)) {
    final name = m.group(1)!;
    final base = h6(m.group(2)!);
    final colors = hex
        .allMatches(m.group(3)!)
        .map((c) => '`${h6(c.group(1)!)}`')
        .join(' ');
    final opacity = double.parse(m.group(4)!).toStringAsFixed(2);
    rows.add('| `$name` | `$base` | $colors | $opacity |');
  }

  if (rows.isEmpty) {
    stderr.writeln('error: no active presets found in _kPresets.');
    exit(1);
  }

  final table = StringBuffer()
    ..writeln('| Preset | Base | Blob colors | Opacity |')
    ..writeln('|--------|------|-------------|---------|')
    ..write(rows.join('\n'));

  const startTag = '<!-- PRESETS:START -->';
  const endTag = '<!-- PRESETS:END -->';
  final block = RegExp(
    '${RegExp.escape(startTag)}.*?${RegExp.escape(endTag)}',
    dotAll: true,
  );

  final readme = readmeFile.readAsStringSync();
  if (!block.hasMatch(readme)) {
    stderr.writeln('error: $startTag / $endTag markers not found in README.md.');
    exit(1);
  }

  final replacement = '$startTag\n'
      '<!-- auto-generated by tool/update_readme.dart — do not edit by hand -->\n'
      '$table\n'
      '$endTag';
  final updated = readme.replaceAll(block, replacement);

  if (updated == readme) {
    stdout.writeln('README already up to date (${rows.length} active presets).');
    return;
  }
  readmeFile.writeAsStringSync(updated);
  stdout.writeln('README presets updated (${rows.length} active).');
}
